Makefile
generate-proto.sh
tools/Makefile

Fix make error from root directory
```
./generate-proto.sh: line 74: goimports: command not found
make: *** [Makefile:4: df-proto] Error 127
```

makefile: add goimports to tools bin

---

go.mod
go.sum
pkg/errors/errors.go
pkg/errors/helper.go
pkg/errors/helper_test.go
pkg/errors/main_test.go
pkg/leakutil/leak_helper.go
pkg/leakutil/leak_helper_test.go

1. Use cdc_errors.RFCCode to check rfc error
2. Use `return rfcError.Wrap(err).GenWithStackByArgs(args...)` to return rfc error wrap
3. Add unit test in errors library.

pkg: fix errors wrap, refine ToPBError, add unit test in errors lib

---

cmd/executor/main.go
executor/runtime/task.go
executor/server.go

Two minor fixes
- Exit executor server when error happens, such as heartbeat timeout.
- Record payload in benchmark demo output.

executor: make executor server exits when error happens

---

cmd/master/example1.toml
master/campaign.go
master/cluster/election.go
master/cluster/election_test.go
master/member.go
master/server.go
pkg/errors/errors.go
pkg/etcdutils/service.go

Finish part of https://github.com/hanfei1991/microcosm/issues/6 and https://github.com/hanfei1991/microcosm/issues/42
- Server master only campaigns to be leader when
- there is no leader
- and this server is etcd leader
- If etcd leader transfers, the server master leader transfers too.

master: check self etcd is leader before campaign leader

---

go.sum
pkg/p2p/message_handler_manager.go
pkg/p2p/message_handler_manager_test.go
pkg/p2p/server.go
pkg/p2p/server_integration_test.go

- Added some adapter logic to make `pkg/p2p` in `tiflow` easier to be used and mocked in Dataflow Engine.

pkg/p2p: add some helper structs for integrating p2p

---

master/cluster/election.go
master/cluster/election_test.go
pkg/errors/errors.go

When a context is Done, it will notify all children context derived from it, and the `ctx.Err()` must return a nil error, otherwise panic will be raised.
```go
panic: context: internal error: missing cancel error
goroutine 8 [running]:
context.(*cancelCtx).cancel(0xc000100080, 0x0, 0x0, 0x0)
/home/apple/.gvm/gos/go1.16.4/src/context/context.go:396 +0x2bb
context.propagateCancel.func1(0x4f01e0, 0xc000100040, 0x4efbb0, 0xc000100080)
/home/apple/.gvm/gos/go1.16.4/src/context/context.go:281 +0x115
created by context.propagateCancel
/home/apple/.gvm/gos/go1.16.4/src/context/context.go:278 +0x1fb
exit status 2
```
A sample reproduce code
```go
package main
import (
"context"
"log"
"time"
)
type customContext struct {
context.Context
}
func newCustomContext(parent context.Context) *customContext …
```

election: fix panic missing cancel error in context

---

master/etcd.go
master/server.go
master/server_test.go

When start a server master, the startup timeout of embed etcd is 1minute, and the startup procedure can't be cancelled before timeout.
- Pass the context to make embed etcd server startup cancelable.

master: make embed etcd server startup cancelable

---

master/server.go
master/server_test.go

Fix the following panic when starting master server
```golang
[2022/01/10 18:07:30.378 +08:00] [INFO] [server.go:503] [payload="address:\"127.0.0.1:10241\" capability:100 "] [request=RegisterExecutor]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf2f5ed]
goroutine 187 [running]:
github.com/hanfei1991/microcosm/master.(*Server).isLeaderAndNeedForward(0xc00010e820, 0x133dd18, 0xc0003b46c0, 0xc000120000)
/home/apple/work/code/pingcap/microcosm/master/server.go:490 +0x30d
github.com/hanfei1991/microcosm/master.(*Server).rpcForwardIfNeeded(0xc00010e820, 0x133dd18, 0xc0003b46c0, 0x112d140, 0xc0003b46f0, 0xf8fa80, 0xc00011a620, 0xc0004d5680, 0xc00039afc0) …
```

master: fix nil leader used in isLeaderAndNeedForward

---

client/master_client.go
cmd/master/example.toml
master/campaign.go
master/config.go
master/member.go
master/member_test.go
master/server.go

- Add a membership interface in server master
- Use `AdvertiseAddr` in member struct, which is more accurate for server discovery.

master: use advertise-addr in server master membership

---

executor/runtime/benchmark/operator.go
test/job_test.go

Fix the following unstable test, try to consume data when executor context is canceled.
```golang
[2022/01/13 03:54:09.128 +00:00] [INFO] [executor_manager.go:77] ["handle heart beat"] [req="executor_id:\"0d0a3a3c-1fb3-46c2-8b3c-b03e49566cd7\" status:1 timestamp:1642046049 ttl:20000001000 "]
[2022/01/13 03:54:09.128 +00:00] [INFO] [server.go:365] ["heartbeat success"] [leader=] [members="[]"]
[2022/01/13 03:54:09.359 +00:00] [INFO] [server.go:508] [payload="executor_id:\"0d0a3a3c-1fb3-46c2-8b3c-b03e49566cd7\" status:1 timestamp:1642046049 ttl:20000001000 "] [request=Heartbeat]
[2022/01/13 03:54:09.360 +00:00] [INFO] [executor_manager.go:77] ["handle heart beat"] [req="executor_id:\"0d0a3a3c-1fb3-46c2-8b3c-b03e49566cd7\" status:1 timestamp:1642046049 ttl:20000001000 "]
[2022/01/13 …
```

test: fix unstable pause job test

---

executor/worker/runtime.go
executor/worker/runtime_test.go
lib/fake/fake_worker.go

This PR implements a simple runtime for worker and implements:
- **Start(conn int)** means starting this runtime, with conn goroutines.
- **AddWorker(lib.Worker)** adds a worker to this runtime
- **Workerload() RescUsage** calculate the sum of running workloads.
I abstract the scheduler to implement more sophisticated algo in the future.
The next PR will connect them with outside world.
ref: #93

executor/worker: new simple runtime

---

executor/runtime/jobmaster/build.go
executor/server.go
pkg/config/constants.go
servermaster/campaign.go
servermaster/config.go

This pr is part of task-2 in #91
- Add `AutoSyncInterval` to etcd config, etcd client will start a goroutine to sync etcd endpoints. See more in https://pkg.go.dev/go.etcd.io/etcd/clientv3#Config
- Extract some constants.

etcd: add AutoSyncInterval config to etcd client

---

executor/server.go
lib/fake/fake_worker.go
lib/registry/factory.go
lib/registry/factory_test.go
lib/registry/registry.go
lib/registry/registry_test.go

- Registry now supports automatically unmarshalling worker configuration in `[]byte`

registry: support passing WorkerConfig

---

executor/server.go
servermaster/etcd_test.go
servermaster/executor_manager.go
servermaster/jobmanager.go
servermaster/server.go

- Abstract interface `ExecutorManager` and `JobManager` in server master
- Fix a panic in executor caused by nil executor info
- Add one unit test in etcd startup function in server master package.

*: abstract some interfaces in server master, fix an executor panic

---

servermaster/config.go
servermaster/executor_manager.go
servermaster/executor_manager_test.go

- Use `KeepAliveInterval` in server master as the executor aliveness check interval.
- Remove unused offline executor channel in executor manager.
- Add unit tests to executor manager.

executor-manager: refine keepalive config, add unit tests

---

executor/cvsTask/cvstask.go
executor/worker/runtime.go
executor/worker/runtime_test.go
lib/common.go
lib/fake/fake_worker.go
lib/master.go
lib/mock_worker_impl.go
lib/worker.go
lib/worker_test.go

- Refined the interface methods of `Master` and `Worker`.
- Extracted `Closer` to define a common `Close` function on both `Master` and `Worker`.

master, worker: refine some API methods

---

servermaster/executor_manager.go
servermaster/resource/capacity_impl.go
servermaster/resource/manager.go

`Reserve` means the expected max resource usage of this node.
`Used` means the resource actually used of this node.
after decoupling resource manager and job master, both of used and reserved resources should be updated by heartbeats.

resource: make heartbeats update reserved resource

---

servermaster/executor_manager_test.go

Fix unstable unit test
```
--- FAIL: TestExecutorManager (0.06s)
executor_manager_test.go:72: 
Error Trace:	executor_manager_test.go:72
Error:      	Not equal: 
expected: 0
actual  : 1
Test:       	TestExecutorManager
FAIL	github.com/hanfei1991/microcosm/servermaster	4.444s
```

test: fix executor timeout is not processed in time

---

executor/server_test.go

Fix the following error
```golang
--- FAIL: TestDiscoveryKeepalive (0.09s)
server_test.go:165: 
Error Trace:	server_test.go:165
Error:      	Not equal: 
expected: 2
actual  : 0
Test:       	TestDiscoveryKeepalive
[2022/01/26 09:26:22.150 +00:00] [ERROR] [http.go:26] ["debug server returned"] [error="mux: server closed"]
[2022/01/26 09:26:22.150 +00:00] [ERROR] [server.go:185] ["close tcp server"] [error="close tcp 127.0.0.1:40721: use of closed network connection"] [errorVerbose="close tcp 127.0.0.1:40721: use of closed network connection\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/juju_adaptor.g …
```

test: fix unstable unit test

---

lib/master.go
lib/worker_manager.go
lib/worker_manager_test.go
pkg/p2p/mock_message_sender.go

- Fix the problem where an executor is offline and the `OnWorkerOfflined` method is not called for affected masters.

master: fix worker offline detection

---

executor/server.go
executor/server_test.go
model/cluster.go
pkg/adapter/keyadapter.go
pkg/srvdiscovery/etcd_impl_test.go
pkg/srvdiscovery/interface.go
pkg/srvdiscovery/runner.go
pkg/srvdiscovery/runner_test.go
servermaster/campaign_test.go
servermaster/executor_manager.go
servermaster/failover.go
servermaster/server.go

Rename `ExecutorInfo` to `NodeInfo`, both server master and executor will store this meta in etcd, which is used in service discovery

*: unify node info for server master and executor

---

lib/master.go
lib/quota/concurrency_quota.go
lib/quota/concurrency_quota_test.go
pkg/errors/errors.go

- Use new goroutines with a concurrency quota to run RPC calls needed by `CreateWorker`.

worker: refine concurrency control of CreateWorker

---

servermaster/member.go
servermaster/member_test.go
servermaster/server.go

Finish #129, server master and executor use the same node info key and form a cluster, and they can be distinguished from `NodeType`.

servermaster: reuse node info key to store server master info

---

go.mod
go.sum
jobmaster/example/master_impl_test.go
lib/common.go
lib/master.go
lib/master_test.go
lib/mock_master_impl.go
lib/worker.go
lib/worker_test.go

- `WorkerStatus` has an `Ext` field which stores an object of a type customized by the business logic.
- In the previous design, the `json` library could not infer the actual type of the object, which could cause failure to deserialize the `WorkerStatus` or other unexpected consequences such as defaulting to `float64` when passing an integer value.
- The problem is solved by adding a method `GetWorkerStatusExtTypeInfo() interface{}` to `MasterImpl`, which provides the necessary type information for `WorkerStatus` to deserialize correctly.

master/worker: fix worker status ext

---

lib/common.go
lib/common_test.go
lib/master.go
test/job_test.go

Fix panic in fake master
```
panic: reflect: Elem of invalid type int64
goroutine 166 [running]:
reflect.(*rtype).Elem(0xfb5860, 0xa, 0xf84320)
/home/apple/.gvm/gos/go1.16.4/src/reflect/type.go:915 +0x1a5
github.com/hanfei1991/microcosm/lib.(*WorkerStatus).fillExt(0xc00090f730, 0xfb5860, 0x1354878, 0x0, 0x0)
/home/apple/work/code/pingcap/microcosm/lib/common.go:86 +0x90
github.com/hanfei1991/microcosm/lib.(*BaseMaster).registerHandlerForWorker.func2(0xc0005ea8d0, 0x24, 0xf84320, 0xc00090f720, 0xc00090f720, 0x0)
/home/apple/work/code/pingcap/microcosm/lib/master.go:376 +0x65
github.com/pingcap/tiflow/pkg/p2p.(*MessageServer).AddHandler.func1(0x1383478, 0xc000090cc0, 0x1056d20, 0xc000970100, 0xc000090d10, 0xc0001629b0)
/home/apple/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/pingcap/tiflo …
```

common: fix panic because of reflect of invalid type

---

executor/cvsTask/cvstask.go
executor/server.go
executor/worker/runtime.go
executor/worker/runtime_test.go
jobmaster/cvsJob/cvsJobMaster.go
lib/common.go
lib/fake/fake_master.go
lib/fake/fake_worker.go
lib/master.go
lib/master_mock_util.go
lib/metadata.go
lib/registry/registry_test.go
lib/worker.go
lib/worker_manager.go
lib/worker_test.go
servermaster/jobmanager_v2.go
servermaster/server.go

- Abstract out the interface `Runnable` which describes an entity that can be run by the runtime.
- Minor modifications to `Worker` interface.
- Minor adjustment of the type of `WorkerID`.
- Abstract out the interface `Workloader`, which describes an object that can report its workload.

runtime, lib: abstract out the interface Runnable

---

sample/3m3e.yaml

- Use different dirs for different master servers.
- Use 0.0.0.0 instead of 127.0.0.1 to listen local port.

sample: fix wrong docker-compose file

---

executor/server.go
executor/worker/internal/runnables.go
executor/worker/runtime.go
executor/worker/runtime_test.go
pkg/errors/errors.go

Fixed the following problem:
- Adding tasks to channels could block the entire runtime.
- `Workload()` could be called on uninitialized tasks.
- Goroutines are not waited for.
- Runtime cannot be canceled from outside.
Added feature:
- Added error type `ErrRuntimeReachedCapacity`
Other:
- Minor adjustment of code styling.

runtime: refine the implementation

---

jobmaster/cvsJob/cvsJobMaster.go
jobmaster/example/master_impl_test.go
lib/base_jobmaster.go
lib/fake/fake_master.go
lib/master.go
lib/master_mock_util.go
lib/mock_master_impl.go
servermaster/jobmanager_v2.go

- Remove `masterClient` and heartbeat logic in `BaseMaster`
- Now job master should implement the interface of `lib.BaseJobMaster`

job-master: remove heartbeat in base master, use job master instead

---

cmd/demoserver/kvdatamake.go
executor/cvsTask/cvstask.go
executor/server.go
executor/worker/internal/runnables.go
jobmaster/cvsJob/cvsJobMaster.go

After this PR, cvsTask can run as expected. In addition:
- adjust log level
- revert the baseJobMaster to baseMaster

fix bugs to run demo

---

executor/server.go
lib/common.go
lib/job.go
lib/master.go
lib/metadata.go
lib/metadata_test.go
pkg/context/context.go
servermaster/job_fsm.go
servermaster/job_fsm_test.go
servermaster/jobmanager.go
servermaster/server.go

To support the job master recover in job manager failover scenario, we should persist enough information of job master.
This PR refactors the storage of `MasterMetaKVData`, renames `JobMasterV2` to `MasterMetaExt` and uses it as a defined type in `MasterMetaKVData`, the `config` defined in `MasterMetaExt` can be parsed by registered `DeserializeConfig` function.
We can use `MasterMetaExt` to restore a complete job.

master: support passing by master meta ext

---

lib/master.go
lib/worker_manager.go

Fix the following panic. Worker status update handler is not removed after worker is offline.
```go
[2022/02/21 01:36:43.980 +08:00] [INFO] [master.go:616] ["Worker dispatched"] [response="error_code:OK worker_id:\"e14847a4-36ab-474b-82ba-fb0b42558f8e\" "]
[2022/02/21 01:36:43.981 +08:00] [PANIC] [status.go:247] ["duplicate handlers"] [topic=worker-status-updated-dataflow-engine-job-manager-e14847a4-36ab-474b-82ba-fb0b42558f8e] [stack="github.com/hanfei1991/microcosm/lib.(*StatusReceiver).Init\n\t/home/apple/work/code/microcosm/lib/status.go:247\ngithub.com/hanfei1991/microcosm/lib.(*workerManagerImpl).addWorker.func1\n\t/home/apple/work/code/microcosm/lib/worker_manager.go:284\ngithub.com/pingcap/tiflow/pkg/workerpool.(*asyncWorker).run\n\t/home/apple/.gvm/pkgsets/go1.17.7/global/pkg/mod/ …
```

lib/master: fix duplicated handler for status update topic

---

servermaster/jobmanager.go

After the refactor https://github.com/hanfei1991/microcosm/pull/193, job manager meta is always overwritten when a new job manager starts(after new server master leader is elected). The `OnMasterRecovered` of job manager is never called.
Since the meta data of job manager is not used, it is safe to overwrite it every time when a new server master leader is elected. And we always mark the Initialized to true in order to trigger `OnMasterRecovered` of job manager.

jobmanager: fix on master recovered is not called

---

pkg/errors/errors.go
servermaster/campaign.go
servermaster/campaign_test.go
servermaster/member.go
servermaster/member_test.go
servermaster/server.go
servermaster/server_test.go
test/etcd_utils.go

Before this PR, each server master uses its embed etcd name as server id, which has one problem in failover scenario.
In the p2p message server, each node should have an unique id, when a server restarts and uses the old id, the other message nodes will ignore all messages of this restarted server, these messages are treated as late messages and ignored.
This PR adds an uuid suffix to etcd name as the server master id.
PR still in wip, need to fix a message flood issue when server master restarts and leader belongs to the same node(same etcd name prefix).

servermaster: add an uuid suffix to server master id

---

lib/common.go
lib/master.go
lib/status.go
lib/worker_manager.go
servermaster/config.go
servermaster/job_fsm.go
servermaster/jobmanager.go

Finish task-3 in #190 
- Export `UnregisterWorker` API in `BaseMaster` interface.
- Check job last ack duration, if it is larger than worker timeout, re create the job master.

servermaster: support checking wait ack job timeout and re-dispatch

---

dm/dump_worker_test.go
dm/load_worker_test.go
dm/sync_worker_test.go
executor/worker/runtime.go
lib/base_jobmaster.go
lib/base_jobmaster_test.go
lib/common.go
lib/fake/fake_master.go
lib/fake/fake_worker.go
lib/master.go
lib/master_test.go
lib/metadata.go
lib/registry/factory_test.go
lib/registry/register_fake.go
lib/registry/registry_test.go
lib/status.go
lib/status_test.go
lib/worker.go
lib/worker_test.go
pkg/errors/errors.go
sample/config/fake_job.json
servermaster/job_fsm.go
servermaster/job_fsm_test.go
servermaster/jobmanager.go

This PR supports worker to exit normally when its worker is done. The changes include
- Remove `Initialized` from `MasterMetaKVData` and add `StatusCode`, which combines the initialization semantic and job master working status.
- Add an `Exit` API in both `BaseJobMaster` and `BaseWorker`, when job master or worker (in user logic code) wants to exit and marks job as finished, it can call the `Exit` function directly.
- After `Exit` is called, base worker will update worker status to finished, and job master will mark master meta to finished to.
- When job manager failovers, it will skip all finished job masters.

worker: support worker finish in one direction

---

executor/cvsTask/cvstask.go
jobmaster/cvsJob/cvsJobMaster.go
lib/worker_manager.go
servermaster/job_fsm.go
servermaster/jobmanager.go

This PR supports cvs job exits when it finishes.
- In both cvs task and cvs job master, call `Exit` when it is finished.
- Support querying finished job in job manager
- Fix several bugs in cvs job, including data race for counter, missing handler for worker if a task finishes before `OnWorkerOnline` is fired.

cvsJob: support normal exit in cvs job

---

servermaster/server.go
servermaster/server_test.go

Fix #224
- `jobManager` is not closed after leader loop exits, just close it.
- The root cause of panic: If we don't close job manager, the registered message handler is not cleaned up and remained in `messageServer`, `messageServer` is a singleton in the server master node. The next time this server node campaigns to be leader and register message handler again, the panic is raised.

servermaster: close job manager after leader exits

---

servermaster/server.go
test/e2e/e2e_test.go

Find this log bumps too much in test, mainly heartbeat rpc from executor.

servermaster: remove forward api log

---

lib/master.go

Fix the following panic.
The root cause is when a job master recovers, the worker could keep sending heartbeat, which is as expected. We must prepare necessary deps before registering message handler, otherwise the job master receives heartbeat and processes without enough deps(workerManager) and leads to panic.
Affected version: https://github.com/hanfei1991/microcosm/commit/ee7f5ffb17ddfbb7e7bd5b686b2506c3d87cac0d
https://github.com/hanfei1991/microcosm/blob/ee7f5ffb17ddfbb7e7bd5b686b2506c3d87cac0d/lib/master.go#L252
```
[2022/03/17 14:58:21.861 +08:00] [INFO] [server.go:189] ["dispatch task"] [req="task_type_id:2 task_config:\"{\\n   \\\"srcHost\\\":\\\"127.0.0.1:1234\\\",\\n   \\\"srcDir\\\":\\\"/home/apple/work/code/microcosm/bin/source\\\",\\n …
```

master: register message handler after workerManager is initialized

---

executor/server.go
lib/worker.go

Since resource broker is not used now, create a fake resource broker temporarily.
Fix panic
```go
[2022/03/21 15:10:22.542 +08:00] [PANIC] [worker.go:123] ["Failed to fill dependencies for BaseWorker"] [error="missing dependencies for function \"reflect\".makeFuncStub (/home/apple/.gvm/gos/go1.17.7/src/reflect/asm_amd64.s:30): missing type: broker.panic: Failed to fill dependencies for BaseWorker                                
goroutine 264 [running]:                                                         
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001709c0, {0xc000d98400, 0x1, 0x1})
/home/apple/.gvm/pkgsets/go1.17.7/global/pkg/mod/go.uber.org/zap@v1.20.0/zapcore/entry.go:232 +0x446
go.uber.org/zap.(*Logger).Panic(0xc000e4c840, {0x462a243, 0xc000989560}, {0xc000d98400, 0x1, 0x1}) …
```

lib/worker: create a fake resource broker temporarily

---

jobmaster/cvsJob/cvsJobMaster.go
lib/fake/fake_master.go
lib/fake/fake_worker.go
lib/status.go
lib/status_test.go
lib/worker.go

- Separate the `SendStatus` into two sub functions, one of them will persist worker status first in a synchronous way, the other function still keeps the asynchronous style.
- Refactor `SafeSendStatus`, it will try to send status in the synchronous way until it is sucessful. This fixes a bug that when there exits a pending message in status sending buffer, the persist worker status could be overlapped with old status.
- Fix in demo job, worker status is not updated to correct value before exiting.

lib/worker: fix data race when updating worker status synchronously

---

lib/common.go
lib/common_test.go
lib/worker_manager.go
lib/worker_manager_test.go

In worker manager, check worker status in each tick, when worker is in terminated state, call `OnWorkerOffline` directly, without waiting for worker heartbeat timeout.

lib/worker: check worker is finished or stopped before timeout

---

lib/fake/fake_master.go
servermaster/job_fsm.go
servermaster/job_fsm_test.go
servermaster/jobmanager.go
servermaster/jobmanager_test.go

Close #266 
- When worker manager starts up, it loads all workers from meta store, but for these tombstone workers no worker offline will be triggered.
- The other workers added by Submit job will be always triggered worker offline.
So in job manager we only filter wait ack jobs for failover only when they are added during job manager failover.

jobmanager: fix job master offline delay caused panic

---

pkg/p2p/server.go

Close #274 
- After this change in `golang.org/x/time` https://github.com/golang/time/commit/f0f3c7e86c11ca8f8b99d970e28445dda0b41195, the behavior of rate limiter with zero limit was changed.
- In dataflow engine, when we create a new p2p server, we didn't pass the value for `SendRateLimitPerStream` at 
https://github.com/pingcap/tiflow/blob/fffe5a1049c8e14caa344cc8bece5648a22ca96c/pkg/p2p/server.go#L645, which will cause this line always fails for the second time it runs and the server receiving loop terminates.  
https://github.com/pingcap/tiflow/blob/fffe5a1049c8e14caa344cc8bece5648a22ca96c/pkg/p2p/server.go#L659

p2p: add one more config in p2p server to avoid stream closed

---

client/master_client.go
client/master_client_test.go
pkg/rpcutil/client.go
pkg/rpcutil/client_test.go

I want to split RPC server/client implementations, like ServerMaster, ResourceManager. For the common need of many types of RPC clients, this PR propose some utility functions. Please see test files to check the usage is acceptable.

provide generics wrapper for RPC client types

---

servermaster/config.go
servermaster/job_fsm.go
servermaster/job_fsm_test.go
servermaster/jobmanager.go
servermaster/jobmanager_test.go

`BaseMaster` provides a `IsMasterReady` API, when this function returns, it means that all tombstone workers have been timeout, and can be recreated safely.
So we can remove the timeout detection in job manager and reuse existing API.

jobmanager: reuse master API for failover of tombstone job master

---

lib/metadata.go
lib/metadata_test.go
servermaster/jobmanager.go
servermaster/jobmanager_test.go

Fix a problem that when create worker returns error during user submit job, the metadata of job master is still kept in metastore. And if the job manager transfers, the failed job master will be failover.
Just remove the master meta if a job is failed to create.

jobmanager: delete master meta when create worker returns error

---

lib/master/worker_manager.go
lib/master/worker_manager_test.go

- Add a fast path for master failover when there is no existing worker in the metastore.

lib/master: optimize for recovering with no worker

---

pkg/srvdiscovery/runner_test.go

Fix the following panic in unit test.
Should print error message instead of panic, use correct parameters in `require.Fail` or `require.Failf`
```go
--- FAIL: TestDiscoveryRunner (8.60s)
panic: interface conversion: interface {} is int, not string [recovered]
panic: interface conversion: interface {} is int, not string
goroutine 124 [running]:
testing.tRunner.func1.2({0x2733340, 0xc0006c5920})
/opt/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1389 +0x[366](https://github.com/hanfei1991/microcosm/runs/6052297129?check_suite_focus=true#step:4:366)
testing.tRunner.func1()
/opt/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1392 +0x5d2
panic({0x2733340, 0xc0006c5920})
/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/panic.go:844 +0x258 …
```

pkg: fix require.fail parameter

---

pkg/srvdiscovery/runner.go
pkg/srvdiscovery/runner_test.go

Close #331
Use fewer runners in unit test, the failed case is often caused by timeout.

pkg: decrease concurrent size to avoid unit test timeout

---

lib/doc/worker_entry_fsm.puml
lib/master/worker_entry.go

- Add a UML version of the state-transition diagram for `workerEntry` used in `WorkerManager`, which is the state management part of `BaseMaster`.

lib/doc: add worker_entry_fsm.puml

---

lib/fake/fake_master.go
lib/fake/fake_worker.go

This PR refines failover in fake master, adding
- A checkpoint in fake master, recording tick status of each worker
- Re-create workers when fake master is failovered.

fake-demo: refine failover in fake master, add simple checkpoint

---

.github/workflows/dataflow_engine_e2e.yaml
lib/fake/fake_master.go
lib/fake/fake_worker.go
test/e2e/e2e_node_chaos_test.go
test/e2e/e2e_test_cli.go

The first part to add node failure test, this PR adds a new feature in fake job.
**Note the real node failure test will be added in next PR.**
- Add there more configurations in fake job config, if `etcd-watch-enable` is true, the fake worker will watch the key of `` etcd-watch-prefix + worker-index ``, any changes will be recorded and increase a mvcc count. The checkpoint is recorded as following. With this feature, we can simulate more failover tests later.
```diff
{
"job-name": "test-fake-job-2",
"worker-count": 3,
"target-tick": 60000,
+    "etcd-watch-enable": true,
+    "etcd-endpoints": ["127.0.0.1:12479"],
+    "etcd-watch-prefix": "/fake-demo/test-2/"
}
```
```go
{"ticks":{"0":24960,"1":24953,"2":24925},
"etcd-checkpoints":{"0":{"revision":701,"mvcc":1,"value":"0x001"},"1":{"revis …
```

e2e: add one more fake job test, to prepare for node failure test

---

executor/server.go
executor/server_test.go

Close #352 
The root cause is executor register itself to server master before server master leader is ready, the executor doesn't handle `MasterNotReady` error and records an empty executor ID.
In later heartbeat request from executor it contains an empty executor ID.
TODO:

executor: retry register when meeting MasterNotReady error

---

lib/master.go
servermaster/jobmanager.go
servermaster/jobmanager_test.go

Close #362 
Job manger should return an error when creating worker meets error `DFLOW:ErrMasterConcurrencyExceeded`, it can retry later.

jobmanager(engine): retry on quota error during create worker

---

servermaster/jobmanager.go
test/e2e/e2e_node_chaos_test.go
test/e2e/e2e_test_cli.go

Fix the second bug in https://github.com/hanfei1991/microcosm/issues/357
When a server master leader restarts, it loads all workers in worker manager. After master is ready, the job manager should clean tombstone workers before re-creating them. Otherwise duplicated entries will be found in worker manger and panic happens.
This bug is also found in existing e2e test
```go
2022-05-10T04:20:12.5745042Z ESC[36;1mserver-master-1_1         |ESC[0m 2022-05-10T04:19:53.284644541Z [2022/05/10 04:19:53.284 +00:00] [INFO] [job_fsm.go:208] ["tombstone job master doesn't receive heartbeat in time, recreate it"] [job="{\"WorkerHandle\":null,\"seq-id\":2,\"created-at\":\"2022-05-10T04:18:37.994Z\",\"updated-at\":\"2022-05-10T04:18:38.017Z\",\"project-id\":\"\",\"id\":\"d571bccf-e8c8-4880-92af-289fa44e12 …
```

jobmanager(engine): clean tombstone worker before failover

---

lib/fake/fake_master.go

Fix the following panic found in test, `workerList` in fake master is a pre-allocated slice with nil pointer.
```golang
2022-05-13T03:25:39.674244547Z [2022/05/13 03:25:39.674 +00:00] [INFO] [task_runner.go:231] ["Task Closed"] [id=83fb921c-6019-4b31-8671-3d2dc27caa2f] [] [runtime-task-count=3]
2022-05-13T03:25:39.676583676Z panic: runtime error: invalid memory address or nil pointer dereference
2022-05-13T03:25:39.676597377Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x411bf41]
2022-05-13T03:25:39.676601177Z
2022-05-13T03:25:39.676604077Z goroutine 1253 [running]:
2022-05-13T03:25:39.676607077Z github.com/hanfei1991/microcosm/lib/fake.(*Master).OnWorkerOffline(0xc0002e7380, {0x5733f68, 0xc001d93260}, {0x56ff5c0?, 0xc001d93248})
2022-05-13T03:25:39.676610277Z …
```

fake(engine): worker could be nil in worker list

---

lib/fake/fake_master.go

- worker list in fake master should be protected by workerListMu.
- Should remove the old handler when worker is offline.

fake(engine): fix concurrent bug and clean handler on worker offline
