README.md
go.mod
master/jobmaster/benchmark/build.go
master/jobmaster/benchmark/master.go

- Add rate limit to task rescheduling when error happens
- Typo fix in readme

jobmaster/demo: add rate limit in benchmark master

---

.golangci.yml
Makefile
executor/jobmanager.go
executor/runtime/build.go
executor/runtime/operator.go
executor/runtime/runtime.go
executor/runtime/task.go
executor/server.go
generate-proto.sh
master/cluster/executor_manager.go
master/server.go
model/cluster.go
model/job.go
pkg/adapter/keyadapter.go
pkg/workerpool/hash.go
tools/check_tidy.sh

- Add check entrypoint in Makefile, including `fmt`, `tidy` and `lint`
- Apply `make fmt`
- Note `make lint` still fails

*: add basic check tools and apply check result

---

master/jobmanager.go
master/jobmaster/benchmark/build.go
master/jobmaster/jobmanager.go
master/jobmaster/system/impl.go
master/jobmaster/system/interface.go
master/server.go

- Refactor the code structure of job master.
- Move some system level code outside demo.

jobmaster: move system level jobmaster code outside demo

---

master/jobmaster/system/impl.go

job-master: wrap job original error

---

README.md
cmd/master/example1.toml
cmd/master/example2.toml
executor/server.go
go.mod
go.sum
master/config.go
master/server.go
pkg/errors/errors.go
pkg/etcdutils/config.go
pkg/etcdutils/join.go
pkg/etcdutils/join_test.go

Add `etcdutils.PrepareJoinEtcd` to support auto join into a etcd cluster.
Most of the codes are copied from dm, and also port unit tests from dm.

server-master: support embed etcd join

---

master/campaign.go
master/cluster/election.go
master/cluster/election_test.go
master/server.go
pkg/errors/errors.go
pkg/etcdclient/client.go
pkg/etcdutils/testing.go

- We need a mockable and testable object for leader elections.

master: implements Election interface

---

client/master_client.go
master/campaign.go
master/member.go
master/server.go
pkg/errors/errors.go

Finish task-1 in https://github.com/hanfei1991/microcosm/issues/42, make server master can forward rpc to leader node.

master: support forward rpc to server master leader

---

README.md
cmd/master/example1.toml
cmd/master/example2.toml
cmd/master/example3.toml

Add a join master config sample, add scheme to `peer-urls` in server master sample config.

server master: refine example config, add a join master sample

---

master/campaign.go
master/server.go

After #66 is fixed, we can resign leader after server master `runLeaderService` exits.
Besides when server master meets `master session done` error, reset etcd session and campaign information.

server-master: resign after leader service exits

---

executor/runtime/benchmark/operator.go
executor/runtime/runtime.go
executor/runtime/task.go

- Fix cpu usage more than 100% when there is no workload on an executor.
- Optimize some string operations in benchmark demo.

executor: fix cpu usage exhaust

---

executor/runtime/benchmark/operator.go

Some operator goroutines still remain when benchmark job is cancelled.

executor: clean exit in some operators

---

jobmaster/system/impl.go
test/job_test.go
test/util_test.go

Before this PR we check running tasks with a 300ms rate limiter, but it will bump too rate limit log every 300ms.
- Change it to a 1s ticker.
- Use free port in unit test instead of hard code ports.

jobmaster: refine check running tasks in job master

---

pkg/adapter/keyadapter.go
pkg/errors/errors.go
pkg/srvdiscovery/etcd_impl.go
pkg/srvdiscovery/etcd_impl_test.go
pkg/srvdiscovery/interface.go

Finish part 1 or https://github.com/hanfei1991/microcosm/issues/91
- Add a service discovery interface, which supports to get a full snapshot, and watches recent changes.
- Add an etcd based service discovery implementation.

pkg: add etcd based service discovery

---

.circleci/config.yml

Add code coverage using [codecov orb](https://circleci.com/developer/orbs/orb/codecov/codecov)

ci: add codecov to calculate coverage

---

Makefile
pkg/srvdiscovery/etcd_impl_test.go
servermaster/member_test.go
test/etcd_utils.go

- Move `PrepareEtcd` into test package
- Add `updateServerMembers` test

membership: add more membership related unit tests

---

.codecov.yml
Makefile

Keep the same config as pingcap/tiflow, except for the default threshold, change from `3%` to `1%`

ci: add codecov config

---

lib/common.go
lib/master_test.go
lib/mock_worker_impl.go
lib/worker.go
lib/worker_manager.go
lib/worker_manager_test.go
lib/worker_test.go
pkg/clock/clock.go

- Add unit test cases for `BaseWorker`.
- Abstracted out `pkg/clock` for mocking the clock.
- Fixed bugs in `BaseWorker`.

worker: add unit test cases

---

cmd/master-client/main.go
servermaster/jobmanager_v2.go

Can also use original submit job command to start a fake job master for test.

servermaster: start fake master from servermaster

---

pkg/errors/errors.go
pkg/metaclient/LICENSE
pkg/metaclient/client.go
pkg/metaclient/common.go
pkg/metaclient/config.go
pkg/metaclient/example.go
pkg/metaclient/kv.go
pkg/metaclient/mockclient.go
pkg/metaclient/op.go

Add kv client abstract interface and usage examples

Add Kv client interface

---

cmd/demoserver/kvdatamake.go

- Fix a bug that demo cvs can't exit after receiving signal such as sigkill. 
- Fix a bug that re-create a cvs job will meet error `[2022/02/18 17:18:36.534 +08:00] [ERROR] [kvdatamake.go:313] ["write data failed  "] ["error   "="write /home/apple/work/code/microcosm/bin/target/4.txt: file already closed"]`.

demoserver: fix deadloop and can't exit normally

---

lib/worker_manager_test.go

Fixed two unstable tests:
- TestHeartBeatPingPongAfterFailover
- TestMultiplePendingHeartbeats

lib: fix unstable tests

---

servermaster/server.go
servermaster/server_test.go

Fix the panic in server master, only collect leader related metrics in leader loop of server master.
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1804449]
goroutine 314 [running]:
github.com/hanfei1991/microcosm/servermaster.(*Server).collectMetricLoop(0xc0002bd7c0, {0x1f75d10, 0xc00087bf00}, 0x0)
/home/apple/work/code/microcosm/servermaster/server.go:716 +0x529
github.com/hanfei1991/microcosm/servermaster.(*Server).Run.func5()
/home/apple/work/code/microcosm/servermaster/server.go:398 +0x2f
golang.org/x/sync/errgroup.(*Group).Go.func1()
/home/apple/.gvm/pkgsets/go1.17.7/global/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by …
```

metrics: fix server master panic because of non leader

---

lib/worker_manager_test.go

Fix the following data race in unit test
```go
==================
WARNING: DATA RACE
Read at 0x00c00088a510 by goroutine 141:
runtime.mapaccess2_faststr()
/home/tidb/.gvm/gos/go1.16.4/src/runtime/map_faststr.go:107 +0x0
github.com/hanfei1991/microcosm/lib.(*workerManagerImpl).getWorkerInfo()
/home/tidb/code/microcosm/lib/worker_manager.go:236 +0x8c
github.com/hanfei1991/microcosm/lib.(*workerManagerImpl).GetWorkerInfo()
/home/tidb/code/microcosm/lib/worker_manager.go:232 +0xd3
github.com/hanfei1991/microcosm/lib.(*workerManagerImpl).addWorker.func1()
/home/tidb/code/microcosm/lib/worker_manager.go:296 +0x114
github.com/pingcap/tiflow/pkg/workerpool.(*asyncWorker).run()
/home/tidb/.gvm/pkgsets/go1.16.4/global/pkg/mod/github.com/pingcap/tiflow@v0.0.0-20220216064339-744a26e0b588/pkg/workerpoo …
```

tests: fix data race in worker manager test

---

dm/dump_worker.go
dm/dump_worker_test.go
dm/load_worker.go
dm/load_worker_test.go
dm/registry.go
dm/sync_worker.go
dm/sync_worker_test.go
jobmaster/example/worker_impl.go
jobmaster/example/worker_impl_test.go
lib/base_jobmaster.go
lib/mock_worker_util.go
lib/worker.go

Signed-off-by: lance6716 <lance6716@gmail.com>

lib.Worker: proxy SendMessage to messageSender

---

lib/fake/fake_master.go
lib/fake/fake_worker.go
lib/status.go

- Make status update in fake job available
- Add a simple dummy worker status struct.

lib/fake: refine status usage in fake job

---

ansible/roles/executor/templates/stop.sh.j2
ansible/roles/master/templates/stop.sh.j2
cmd/demoserver/kvdatamake.go

1. flush the file which this thread is in charge of
2. fix stop command

fix a demo race bug on file writer

---

lib/worker.go
lib/worker_test.go

lib/worker: fix panic caused by closing before init'ing

---

executor/worker/runtime_test.go
executor/worker/task_runner.go
executor/worker/task_runner_test.go
executor/worker/test_util.go
pkg/errors/errors.go

- Created `TaskRunner` which uses dedicated goroutines to run each task.

executor/runtime: implement a new runtime with separate goroutines per task

---

servermaster/job_fsm.go
servermaster/job_fsm_test.go

- A job master could finish before `OnWorkerOnline` is called, in this scenario the job should be removed from wait ack list when `OnWorkerOffline` is called.
- Refine the state transition diagram of job manager

jobmanager: fix job is not removed from ack list if it finishes before online

---

executor/server.go
pkg/errors/errors.go
sample/1m1e.yaml
sample/1m3e.yaml
sample/3m3e.yaml
sample/config/etcd.yml
servermaster/config.go
servermaster/config_test.go
servermaster/server.go

replace the etcd listening host and fix config error

fix(deployment): fix metastore config and deployment error

---

.github/workflows/dataflow_engine_e2e.yaml
sample/prepare.sh

Only run case TestSubmitTest currently

ci: add e2e test in github action

---

ansible/group_vars/all
ansible/roles/common/tasks/main.yml
ansible/roles/master/tasks/main.yml
ansible/roles/master/tasks/start.yml
ansible/roles/master/templates/etcd.yml.j2
ansible/roles/master/templates/start.sh.j2
ansible/roles/master/templates/stop.sh.j2

Deploy etcd in where master runs

ansible: support etcd

---

go.mod
lib/message_router.go
lib/metadata.go
lib/model/status.go
lib/model/status_test.go
lib/statusutil/writer.go
lib/statusutil/writer_test.go

lib: fix key encoding for WorkerStatus

---

lib/worker.go
lib/worker_manager.go

*: fix two issues

---

.github/workflows/dataflow_engine_e2e.yaml
sample/1m1e.yaml
sample/config/mysql.cnf
sample/dm_databases.yaml
test/utils/wait_mysql_online.sh

ci: support dm e2e test in github action

---

.golangci.yml
pkg/externalresource/manager/client.go
pkg/externalresource/manager/service.go
pkg/externalresource/manager/service_test.go
pkg/rpcutil/server.go
pkg/rpcutil/server_test.go
servermaster/campaign.go
servermaster/campaign_test.go
servermaster/executor_manager.go
servermaster/member.go
servermaster/member_test.go
servermaster/server.go
servermaster/server_test.go

- register gRPC for resource manager
- use `rpcutil` to implement leader forwarding
ref https://github.com/hanfei1991/microcosm/issues/235

register gRPC for resource manager

---

pkg/meta/kvclient/etcdkv/etcd_client.go
pkg/meta/kvclient/mock/simple_mockclient.go
pkg/meta/kvclient/mock/simple_mockclient_test.go
pkg/meta/namespace/kv_test.go

close  issue: #289 
meta mock support serialize level txn

fix(mock): meta mock support txn and fix txn panic

---

dm/dump_worker_test.go
dm/load_worker_test.go
dm/sync_worker_test.go
executor/server.go
lib/common.go
lib/master.go
lib/master_test.go
lib/metadata/metadata.go
lib/metadata/metadata_test.go
lib/mock_master_util.go
lib/worker.go
lib/worker_manager.go
lib/worker_manager_test.go
lib/worker_test.go
servermaster/job_fsm.go
servermaster/job_fsm_test.go
servermaster/jobmanager.go
servermaster/jobmanager_test.go
servermaster/server.go

- Put master-worker metadata to a separate package

lib: split out lib/metadata

---

tools/Makefile
tools/go.mod
tools/go.sum
tools/tools.go

Some binaries in tools are not used, just remove them.

ci: remove unused tools

---

lib/worker_test.go
servermaster/cluster/election_test.go

*: stable unit test

---

servermaster/jobmanager.go

Ref: https://github.com/hanfei1991/microcosm/issues/325
During job manager failover, after `IsMasterReady` returns true, fetch all workers via `GetWorkers` API in lib/master and records the worker online information in job manager.

jobmanager: query online worker after master is ready in failover

---

executor/worker/task_committer.go
executor/worker/task_committer_test.go
executor/worker/task_runner.go
executor/worker/task_runner_test.go

- Part I of implementing two-phase create worker.

runtime: implement TaskCommitter

---

lib/master/worker_handle.go
lib/master/worker_manager.go
lib/master/worker_manager_test.go

lib/master: fix CleanTombstone not cleaning memory state

---

pkg/errors/errors.go
pkg/rpcutil/client.go
pkg/rpcutil/client_test.go

fix violation when no available RPC clients

---

lib/master/worker_manager.go
lib/master/worker_manager_test.go

- Stabilize test `TestRecoverAfterFailover` and `TestRecoverAfterFailoverFast`.

lib/master: stabilize TestRecoverAfterFailover

---

executor/server.go

executor: Allow MasterNotReady as valid heartbeat response

---

executor/server.go
lib/statusutil/master_info.go
lib/statusutil/writer.go
lib/statusutil/writer_test.go
lib/worker.go
lib/worker_test.go

lib: trigger a masterInfo refresh if the master node is not found

---

pkg/orm/mock.go
pkg/orm/mock_test.go

ref:https://www.sqlite.org/inmemorydb.html
using dsn(file:%s?mode=memory&cache=shared) format here to
1. Create different DB for different TestXXX()
2. Enable DB shared for different connection

fix(orm): using more proper dsn for sqlite

---

pkg/containers/chunked_queue.go
pkg/containers/queue.go
pkg/containers/slice_queue.go
pkg/containers/slice_queue_test.go
pkg/notifier/notifier.go
pkg/notifier/notifier_test.go

- Implemented a Single-Producer Multiple-Consumer event notifier.

pkg/notifier: implement notifier
